In [1]:
a = [1.0, 2.0, 1.0]

In [2]:
a[0]

1.0

In [3]:
a[2]

1.0

In [4]:
a

[1.0, 2.0, 1.0]

In [5]:
import torch

In [6]:
# PyTorch tensors or NumPy arrays, 
# on the other hand, are views over (typically) contiguous memory 
# blocks containing unboxed C numeric types rather than Python objects

In [7]:
a = torch.ones(3)
a

tensor([1., 1., 1.])

In [8]:
print(a.shape)

torch.Size([3])


In [9]:
a[1]

tensor(1.)

In [10]:
float(a[1])

1.0

In [11]:
a[2] = 2.0
a

tensor([1., 1., 2.])

In [12]:
a.ndim

1

In [13]:
# a[0] = 'strr' # Tensors are homogeneous (i.e., all elements are of the same data type)

In [14]:
# Say we have a list of coordinates we’d like to use to represent a geometrical object: perhaps a 2D triangle with vertices
# at coordinates (4, 1), (5, 3), and (2, 1)

In [15]:
points = torch.ones(6)
points[0] = 4
points[1] = 1
points[2] = 5
points[3] = 3
points[4] = 2
points[5] = 1
points

tensor([4., 1., 5., 3., 2., 1.])

In [16]:
# or pass a list

In [17]:
points = torch.tensor([4.0, 1.0, 5.0, 3.0, 2.0, 1.0])
points

tensor([4., 1., 5., 3., 2., 1.])

In [18]:
float(points[0]), float(points[1])

(4.0, 1.0)

In [19]:
points = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]])
points

tensor([[4., 1.],
        [5., 3.],
        [2., 1.]])

In [20]:
print(points.shape)

torch.Size([3, 2])


In [21]:
print(points.ndim)

2


In [22]:
#points = torch.zeros(3,2)
#points

In [23]:
#print(points.shape)

In [24]:
points[0,1]

tensor(1.)

In [25]:
points[0] # The output is another tensor that presents a different view of the same underlying data

tensor([4., 1.])

## Indexing tensors

In [26]:
some_list = list(range(6))
some_list

[0, 1, 2, 3, 4, 5]

In [27]:
some_list[:]

[0, 1, 2, 3, 4, 5]

In [28]:
some_list[1:4]

[1, 2, 3]

In [29]:
some_list[1:]

[1, 2, 3, 4, 5]

In [30]:
some_list[:4]

[0, 1, 2, 3]

In [31]:
some_list[:-1]

[0, 1, 2, 3, 4]

In [32]:
some_list[1:4:2]

[1, 3]

In [33]:
points[1:]

tensor([[5., 3.],
        [2., 1.]])

In [34]:
points[1:, :]

tensor([[5., 3.],
        [2., 1.]])

In [35]:
points[1:, 0]

tensor([5., 2.])

In [36]:
points[None]

tensor([[[4., 1.],
         [5., 3.],
         [2., 1.]]])

In [37]:
points[None].shape # Adds a dimension of size 1; the same can be accomplished with points.unsqueeze(dim=0).

torch.Size([1, 3, 2])

## Broadcasting

In [38]:
# PyTorch will allow us to multiply things that are the same shape, as well as shapes where one operand is of size 1 in a given dimension.
# It also appends the leading dimensions of size 1 automatically.

In [39]:
torch.tensor([[1,2,3]]) + 10

tensor([[11, 12, 13]])

In [40]:
torch.tensor([[1, 2, 3]]) * torch.tensor([[10],[20],[30]]) # shape(1,3) * shape(3,1) = shape(3,3)

tensor([[10, 20, 30],
        [20, 40, 60],
        [30, 60, 90]])

In [41]:
torch.tensor([[1, 2, 3], [4, 5, 6]]) + torch.tensor([[[10, 20, 30]], [[40, 50, 60]]]) # shape(2,3) + shape(2, 1, 3) = shape(2,2,3)

tensor([[[11, 22, 33],
         [14, 25, 36]],

        [[41, 52, 63],
         [44, 55, 66]]])

## Named tensors

In [42]:
img_t = torch.randn(3, 5, 5) # shape(3,5,5) => shape [channels (RGB), rows, columns]
weights = torch.tensor([0.2126, 0.7152, 0.0722])
weights.shape

torch.Size([3])

In [43]:
batch_t = torch.randn(2, 3, 5, 5) # shape(2, 3, 5, 5) => shape [batch, channels (RGB), rows, columns]

In [44]:
img_gray_naive = img_t.mean(-3) # lazy, unweighted mean on dimension -3 (channel)
img_gray_naive

tensor([[ 0.3938,  0.1450, -0.2340,  0.7167, -0.0855],
        [ 0.9963, -0.8459,  0.2214, -0.2339,  0.4209],
        [-0.1081, -0.1703, -1.7886,  0.7642, -0.3651],
        [-0.2951,  1.0331, -0.2989, -0.1525,  0.4390],
        [ 0.8819,  0.5730, -1.5757, -0.6886, -0.6399]])

In [45]:
batch_gray_naive = batch_t.mean(-3) # again lazy, unweighted mean on dimension -3 (channel)
batch_gray_naive

tensor([[[-0.9456,  0.2289, -0.5438,  0.9790, -0.2097],
         [ 0.5536, -0.5202, -0.7828, -0.3334,  0.1429],
         [ 0.2789,  0.3522, -0.9145, -0.2802, -0.4939],
         [ 0.7546,  0.7414, -0.0228, -0.5445,  0.1491],
         [-0.9669, -0.2421,  0.8230, -0.1564,  0.7429]],

        [[ 1.1208, -0.2809,  0.0685,  0.1694, -0.3558],
         [ 1.3637, -0.6778, -0.1004, -0.3974, -0.4386],
         [ 0.0383, -1.2936,  0.1001,  1.0302, -0.1709],
         [ 0.6316,  0.8147, -0.0570,  1.0245,  0.7298],
         [ 0.8443, -0.5263, -0.0625,  0.1342, -0.2101]]])

In [46]:
img_gray_naive.shape, batch_gray_naive.shape

(torch.Size([5, 5]), torch.Size([2, 5, 5]))

In [47]:
unsqueezed_weights = weights.unsqueeze(-1).unsqueeze(-1) # shape(3,1,1)
unsqueezed_weights

tensor([[[0.2126]],

        [[0.7152]],

        [[0.0722]]])

In [48]:
img_weights = img_t * unsqueezed_weights # shape(3,5,5)
img_weights

tensor([[[ 0.2487,  0.0694, -0.4523,  0.3659,  0.1419],
         [ 0.0871, -0.1337,  0.0818, -0.0863, -0.0420],
         [-0.2914, -0.1456, -0.1790,  0.2487, -0.2894],
         [-0.3472,  0.4121,  0.0238, -0.0176, -0.1044],
         [ 0.3480,  0.4414, -0.3514, -0.0928, -0.4095]],

        [[ 0.1124,  0.5758,  0.1183,  0.3900, -1.0062],
         [ 1.4610, -0.4751, -0.1565, -0.1876, -0.0413],
         [-0.6769,  0.5047, -1.2386,  0.5262,  0.5872],
         [ 0.9091,  0.2850, -1.0690, -0.3666,  0.3263],
         [ 0.0291, -0.0333, -0.8282, -0.2317,  0.5411]],

        [[-0.0105, -0.0503,  0.0910, -0.0084,  0.0349],
         [ 0.0387, -0.0898,  0.0360, -0.0024,  0.1096],
         [ 0.1439, -0.0384, -0.2016,  0.0279, -0.0401],
         [-0.0378,  0.0550,  0.0351,  0.0100,  0.0976],
         [ 0.0699, -0.0224, -0.1383, -0.0942, -0.0542]]])

In [49]:
batch_weights = batch_t * unsqueezed_weights # shape(2,3,5,5) remember that broadcasting appends the leading dimensions of size 1 automatically
batch_weights

tensor([[[[-1.9522e-01,  2.0376e-01, -1.4474e-01,  2.0597e-02, -1.0970e-01],
          [ 1.1615e-01,  5.0400e-02, -7.5354e-02, -1.6487e-01, -9.4834e-02],
          [-1.7836e-03,  1.1193e-01, -3.0264e-01, -3.2248e-02, -2.5539e-01],
          [ 1.0065e-01,  3.3401e-02,  3.1305e-02, -4.7521e-02,  2.0553e-02],
          [-5.7317e-01, -1.5321e-01,  2.7157e-01,  2.0914e-02, -1.6934e-02]],

         [[ 1.1878e-01,  9.3067e-04, -3.6276e-01,  5.7154e-01, -2.0243e-01],
          [ 1.0087e-01, -1.1349e+00, -5.7048e-01, -4.0666e-01,  3.1526e-01],
          [-1.2945e-01,  1.4170e+00, -4.7083e-01, -7.7754e-01,  1.3705e-01],
          [ 1.0354e+00,  3.1847e-01, -1.2490e+00, -1.0213e+00,  3.0733e-02],
          [-2.5898e-01, -1.9091e-01,  9.9557e-01, -3.5734e-01,  2.0301e+00]],

         [[-1.5052e-01, -1.9706e-02, -3.2019e-02,  1.4735e-01,  1.2274e-02],
          [ 7.0272e-02, -1.5222e-02, -8.6374e-02,  2.4825e-02,  3.1326e-02],
          [ 7.4090e-02, -1.0476e-01, -4.7769e-02,  2.8744e-02, -3.4078e-

In [50]:
img_gray_weighted = img_weights.sum(-3) # sum on third dimension from the end (channel), shape(5,5)
img_gray_weighted

tensor([[ 0.3506,  0.5950, -0.2430,  0.7475, -0.8294],
        [ 1.5868, -0.6986, -0.0388, -0.2763,  0.0263],
        [-0.8245,  0.3208, -1.6192,  0.8028,  0.2577],
        [ 0.5241,  0.7521, -1.0101, -0.3742,  0.3196],
        [ 0.4470,  0.3856, -1.3180, -0.4187,  0.0775]])

In [51]:
batch_gray_weighted = batch_weights.sum(-3) # sum on third dimension from the end (channel), shape(2,5,5)
batch_gray_weighted

tensor([[[-0.2270,  0.1850, -0.5395,  0.7395, -0.2998],
         [ 0.2873, -1.0997, -0.7322, -0.5467,  0.2517],
         [-0.0571,  1.4241, -0.8212, -0.7810, -0.1524],
         [ 1.1608,  0.4690, -1.1072, -1.0676,  0.0735],
         [-0.8208, -0.3253,  1.2527, -0.3413,  1.9749]],

        [[ 0.8687, -0.8225,  0.5031, -0.2699, -0.6529],
         [ 2.2838, -0.6967, -0.1670, -0.3227, -1.0103],
         [ 0.4807, -1.5275,  0.5989,  1.6508, -0.0629],
         [ 0.0241,  0.2347, -0.2420,  0.7714,  1.0807],
         [ 0.3009, -0.2972,  0.0855, -0.0141, -0.2513]]])

In [52]:
batch_weights.shape, batch_t.shape, unsqueezed_weights.shape

(torch.Size([2, 3, 5, 5]), torch.Size([2, 3, 5, 5]), torch.Size([3, 1, 1]))

In [53]:
weights_named = torch.tensor([0.2126, 0.7152, 0.0722], names = ['channels'])
weights_named

/var/folders/bs/9j5t349d48g3lctd8l3l5l1r0000gn/T/ipykernel_84340/2163324119.py:1: UserWarning: Named tensors and all their associated APIs are an experimental feature and subject to change. Please do not use them for anything important until they are released as stable. (Triggered internally at /Users/runner/work/pytorch/pytorch/pytorch/c10/core/TensorImpl.h:1976.)
  weights_named = torch.tensor([0.2126, 0.7152, 0.0722], names = ['channels'])


tensor([0.2126, 0.7152, 0.0722], names=('channels',))

In [54]:
print(weights_named.shape, weights_named.names)

torch.Size([3]) ('channels',)


In [55]:
img_t_named = img_t.refine_names(..., 'channels', 'rows', 'columns')
batch_t_named = batch_t.refine_names(..., 'channels', 'rows', 'columns')
print("img named: ", img_t_named.shape, img_t_named.names)
print("batch named: ", batch_t_named.shape, batch_t_named.names)

img named:  torch.Size([3, 5, 5]) ('channels', 'rows', 'columns')
batch named:  torch.Size([2, 3, 5, 5]) (None, 'channels', 'rows', 'columns')


In [56]:
# For operations with two inputs, in addition to the usual dimension checks—whether sizes are the same, 
# or if one is 1 and can be broadcast to the other—PyTorch will now check the names for us. 
# So far, it does not automatically align dimensions, so we need to do this explicitly.
# The method align_as returns a tensor with missing dimensions added and existing ones permuted to the right order

In [57]:
weights_named_aligned = weights_named.align_as(img_t_named)
weights_named_aligned.shape, weights_named_aligned.names

(torch.Size([3, 1, 1]), ('channels', 'rows', 'columns'))

In [58]:
# Functions accepting dimension arguments, like sum, also take named dimensions
gray_named = (img_t_named * weights_named_aligned).sum('channels')
gray_named

tensor([[ 0.3506,  0.5950, -0.2430,  0.7475, -0.8294],
        [ 1.5868, -0.6986, -0.0388, -0.2763,  0.0263],
        [-0.8245,  0.3208, -1.6192,  0.8028,  0.2577],
        [ 0.5241,  0.7521, -1.0101, -0.3742,  0.3196],
        [ 0.4470,  0.3856, -1.3180, -0.4187,  0.0775]],
       names=('rows', 'columns'))

In [59]:
img_t_named[...,:3]

tensor([[[ 1.1697,  0.3265, -2.1276],
         [ 0.4099, -0.6290,  0.3849],
         [-1.3707, -0.6846, -0.8420],
         [-1.6330,  1.9385,  0.1118],
         [ 1.6370,  2.0760, -1.6531]],

        [[ 0.1571,  0.8051,  0.1654],
         [ 2.0427, -0.6643, -0.2189],
         [-0.9465,  0.7057, -1.7319],
         [ 1.2711,  0.3985, -1.4946],
         [ 0.0407, -0.0466, -1.1581]],

        [[-0.1455, -0.6966,  1.2602],
         [ 0.5362, -1.2444,  0.4982],
         [ 1.9928, -0.5319, -2.7919],
         [-0.5233,  0.7624,  0.4860],
         [ 0.9680, -0.3104, -1.9159]]], names=('channels', 'rows', 'columns'))

In [60]:
# gray_named = (img_t_named[...,:3] * weights_named).sum('channels') # doesn't work

In [61]:
# If we want to use tensors outside functions that operate on named tensors, we need to drop the names by renaming them to None.
# The following gets us back into the world of unnamed dimensions
gray_plain = gray_named.rename(None)
gray_plain.shape, gray_plain.names

(torch.Size([5, 5]), (None, None))

## Tensor element types. dtype

In [62]:
# the objects within a tensor must all be numbers of the same type, and PyTorch must keep track of this numeric type.

In [63]:
# torch.float32 or torch.float—32-bit floating-point
# torch.float64 or torch.double—64-bit, double-precision floating-point
# torch.complex64 or torch.cfloat—64-bit complex
# torch.complex128 or torch.cdouble—128-bit complex
# torch.float16 or torch.half—16-bit, half-precision floating-point
# torch.bfloat16—brain float 16-bit, half-precision floating-point (This is a new data type introduced by Google in 2019. It is similar to torch.float16 but uses a different encoding that can encode a larger range, while float16 is better for precision.)
# torch.int8—signed 8-bit integers
# torch.uint8—unsigned 8-bit integers
# torch.int16 or torch.short—signed 16-bit integers
# torch.int32 or torch.int—signed 32-bit integers
# torch.int64 or torch.long—signed 64-bit integers
# torch.bool—Boolean
# The default data type for tensors is 32-bit floating-point.

In [64]:
double_points = torch.ones(10, 2, dtype=torch.double)
double_points

tensor([[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]], dtype=torch.float64)

In [65]:
short_points = torch.tensor([[1,2],[3,4]], dtype=torch.short)
short_points

tensor([[1, 2],
        [3, 4]], dtype=torch.int16)

In [66]:
# casting
double_points = torch.zeros(10,2).double()
short_points = torch.ones(10,2).short()
double_points, short_points

(tensor([[0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.]], dtype=torch.float64),
 tensor([[1, 1],
         [1, 1],
         [1, 1],
         [1, 1],
         [1, 1],
         [1, 1],
         [1, 1],
         [1, 1],
         [1, 1],
         [1, 1]], dtype=torch.int16))

In [67]:
# or
double_points = torch.zeros(10,2).to(torch.double)
short_points = torch.ones(10,2).to(dtype=torch.short)
double_points, short_points

(tensor([[0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.]], dtype=torch.float64),
 tensor([[1, 1],
         [1, 1],
         [1, 1],
         [1, 1],
         [1, 1],
         [1, 1],
         [1, 1],
         [1, 1],
         [1, 1],
         [1, 1]], dtype=torch.int16))

In [68]:
# when mixing input types in operations, the inputs are converted to the larger type automatically

In [69]:
points_64 = torch.rand(5, dtype=torch.double) # rand initializes the tensor elements to random numbers between 0 and 1.
points_short = points_64.to(torch.short)
points_64 * points_short

tensor([0., 0., 0., 0., 0.], dtype=torch.float64)

## Tensor API

In [70]:
a = torch.ones(3,2)
a

tensor([[1., 1.],
        [1., 1.],
        [1., 1.]])

In [71]:
a_t = torch.transpose(a, 0, 1)
a.shape, a_t.shape

(torch.Size([3, 2]), torch.Size([2, 3]))

In [72]:
# or
a_t = a.transpose(0,1)
a_t.shape

torch.Size([2, 3])

## Indexing into storage

In [73]:
points = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]])
points.storage()

/var/folders/bs/9j5t349d48g3lctd8l3l5l1r0000gn/T/ipykernel_84340/2923139482.py:2: UserWarning: TypedStorage is deprecated. It will be removed in the future and UntypedStorage will be the only storage class. This should only matter to you if you are using storages directly.  To access UntypedStorage directly, use tensor.untyped_storage() instead of tensor.storage()
  points.storage()


 4.0
 1.0
 5.0
 3.0
 2.0
 1.0
[torch.storage.TypedStorage(dtype=torch.float32, device=cpu) of size 6]

In [74]:
# We can’t index a storage of a 2D tensor using two indices. The layout of a storage is always one-dimensional,
# regardless of the dimensionality of any and all tensors that might refer to it.

In [75]:
points.storage()[1]

1.0

In [76]:
points_storage = points.storage()

In [77]:
points_storage[0] = 2.0
points

tensor([[2., 1.],
        [5., 3.],
        [2., 1.]])

###  In-place operations

In [78]:
# In addition to the operations on tensors introduced in the previous section,
# a small number of operations exist only as methods of the Tensor object.
# They are recognizable from a trailing underscore in their name,
# like zero_, which indicates that the method operates in place by modifying the input instead of creating a new output tensor and returning it.
# For instance, the zero_ method zeros out all the elements of the input. 
# Any method without the trailing underscore leaves the source tensor unchanged and instead returns a new tensor:

In [79]:
a = torch.ones(3,2)
a.zero_()
a

tensor([[0., 0.],
        [0., 0.],
        [0., 0.]])

## Tensor metadata: Size, offset, and stride

In [80]:
# The size (or shape, in NumPy parlance) is a tuple indicating the number of elements across each dimension the tensor represents.
# The storage offset is the index in the storage corresponding to the first element in the tensor.
# The stride (ШАГ) is the number of elements in the storage that need to be skipped over to obtain the next element along each dimension.

In [81]:
points = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]])
second_point = points[1]

In [82]:
second_point.storage_offset()

2

In [83]:
second_point.size()

torch.Size([2])

In [84]:
second_point.shape

torch.Size([2])

In [85]:
# The stride is a tuple indicating the number of elements in the storage that have to be skipped when the index is increased by 1 in each dimension.

In [86]:
points.stride()

(2, 1)

In [87]:
# Accessing an element i, j in a 2D tensor results in accessing the storage_offset + stride[0] * i + stride[1] * j element in the storage.
# The offset will usually be zero; if this tensor is a view of a storage created to hold a larger tensor, the offset might be a positive value.

In [88]:
second_point.size()

torch.Size([2])

In [89]:
second_point.stride()

(1,)

In [90]:
second_point[0] = 10.0

In [91]:
points

tensor([[ 4.,  1.],
        [10.,  3.],
        [ 2.,  1.]])

In [92]:
second_point = points[1].clone() # create dedicated Storage
second_point[0] = 10.1
points

tensor([[ 4.,  1.],
        [10.,  3.],
        [ 2.,  1.]])

## Transposing w/o copying

In [93]:
points_t = points.t()
points_t

tensor([[ 4., 10.,  2.],
        [ 1.,  3.,  1.]])

In [94]:
id(points.storage()) == id(points_t.storage()) # same storage

True

In [95]:
#  transposing is obtained only by creating a new Tensor instance with different stride ordering than the original.

In [96]:
points.stride(), points_t.stride() # interesting ! as storage is the same and points_t is just a view inside the same storage

((2, 1), (1, 2))

In [97]:
points.storage()

 4.0
 1.0
 10.0
 3.0
 2.0
 1.0
[torch.storage.TypedStorage(dtype=torch.float32, device=cpu) of size 6]

## Transposing in higher dimensions

In [98]:
# Transposing in PyTorch is not limited to matrices.
# We can transpose a multidimensional array by specifying the two dimensions along which transposing (flipping shape and stride) should occur

In [99]:
some = torch.ones(3,4,5)
some_t = some.transpose(0,2)
some.shape, some_t.shape

(torch.Size([3, 4, 5]), torch.Size([5, 4, 3]))

In [100]:
some.stride(), some_t.stride()

((20, 5, 1), (1, 5, 20))

## Contiguous tensors

In [101]:
points.is_contiguous()

True

In [102]:
points_t.is_contiguous()

False

In [103]:
# We can obtain a new contiguous tensor from a noncontiguous one using the contiguous method. 
# The content of the tensor will be the same, but the stride will change because we are essentially rearranging the values in a new storage

In [104]:
points_t

tensor([[ 4., 10.,  2.],
        [ 1.,  3.,  1.]])

In [105]:
points_t.storage()

 4.0
 1.0
 10.0
 3.0
 2.0
 1.0
[torch.storage.TypedStorage(dtype=torch.float32, device=cpu) of size 6]

In [106]:
points_t.stride()

(1, 2)

In [107]:
points_t_cont = points_t.contiguous()
points_t_cont

tensor([[ 4., 10.,  2.],
        [ 1.,  3.,  1.]])

In [108]:
points_t_cont.storage()

 4.0
 10.0
 2.0
 1.0
 3.0
 1.0
[torch.storage.TypedStorage(dtype=torch.float32, device=cpu) of size 6]

In [109]:
points_t_cont.stride()

(3, 1)

## Managing a tensor’s device attribute

In [110]:
points_gpu = points.to(device="mps") # copying a tensor created on gpu to mps

In [111]:
points_gpu

tensor([[ 4.,  1.],
        [10.,  3.],
        [ 2.,  1.]], device='mps:0')

In [112]:
points_cpu = points_gpu.cpu()
points_cpu

tensor([[ 4.,  1.],
        [10.,  3.],
        [ 2.,  1.]])

## NumPY

In [119]:
points_np = points.numpy() # returned array shares the same underlying buffer with the tensor storage
points_np

array([[ 5.,  5.],
       [10.,  3.],
       [ 2.,  1.]], dtype=float32)

In [118]:
points_np[0,0] = 5.0 # means modifying the NumPy array will lead to a change in the originating tensor
points

tensor([[ 5.,  5.],
        [10.,  3.],
        [ 2.,  1.]])

## Serializing tensors

In [120]:
torch.save(points, "../data/p1ch03/points.t") # the file format itself is not interoperable: we can’t read the tensor with software other than PyTorch

In [122]:
with open("../data/p1ch03/points.t", "rb") as f:
    new_points = torch.load(f)
new_points

tensor([[ 5.,  5.],
        [10.,  3.],
        [ 2.,  1.]])