In [1]:
a = [1.0, 2.0, 1.0]

In [2]:
a[0]

1.0

In [3]:
a[2]

1.0

In [4]:
a

[1.0, 2.0, 1.0]

In [5]:
import torch

In [6]:
# PyTorch tensors or NumPy arrays, 
# on the other hand, are views over (typically) contiguous memory 
# blocks containing unboxed C numeric types rather than Python objects

In [7]:
a = torch.ones(3)
a

tensor([1., 1., 1.])

In [8]:
print(a.shape)

torch.Size([3])


In [9]:
a[1]

tensor(1.)

In [10]:
float(a[1])

1.0

In [11]:
a[2] = 2.0
a

tensor([1., 1., 2.])

In [12]:
a.ndim

1

In [13]:
# a[0] = 'strr' # Tensors are homogeneous (i.e., all elements are of the same data type)

In [14]:
# Say we have a list of coordinates we’d like to use to represent a geometrical object: perhaps a 2D triangle with vertices
# at coordinates (4, 1), (5, 3), and (2, 1)

In [15]:
points = torch.ones(6)
points[0] = 4
points[1] = 1
points[2] = 5
points[3] = 3
points[4] = 2
points[5] = 1
points

tensor([4., 1., 5., 3., 2., 1.])

In [16]:
# or pass a list

In [17]:
points = torch.tensor([4.0, 1.0, 5.0, 3.0, 2.0, 1.0])
points

tensor([4., 1., 5., 3., 2., 1.])

In [18]:
float(points[0]), float(points[1])

(4.0, 1.0)

In [19]:
points = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]])
points

tensor([[4., 1.],
        [5., 3.],
        [2., 1.]])

In [20]:
print(points.shape)

torch.Size([3, 2])


In [21]:
print(points.ndim)

2


In [22]:
#points = torch.zeros(3,2)
#points

In [23]:
#print(points.shape)

In [24]:
points[0,1]

tensor(1.)

In [25]:
points[0] # The output is another tensor that presents a different view of the same underlying data

tensor([4., 1.])

## Indexing tensors

In [26]:
some_list = list(range(6))
some_list

[0, 1, 2, 3, 4, 5]

In [27]:
some_list[:]

[0, 1, 2, 3, 4, 5]

In [28]:
some_list[1:4]

[1, 2, 3]

In [29]:
some_list[1:]

[1, 2, 3, 4, 5]

In [30]:
some_list[:4]

[0, 1, 2, 3]

In [31]:
some_list[:-1]

[0, 1, 2, 3, 4]

In [32]:
some_list[1:4:2]

[1, 3]

In [33]:
points[1:]

tensor([[5., 3.],
        [2., 1.]])

In [34]:
points[1:, :]

tensor([[5., 3.],
        [2., 1.]])

In [35]:
points[1:, 0]

tensor([5., 2.])

In [36]:
points[None]

tensor([[[4., 1.],
         [5., 3.],
         [2., 1.]]])

In [37]:
points[None].shape # Adds a dimension of size 1; the same can be accomplished with points.unsqueeze(dim=0).

torch.Size([1, 3, 2])

## Broadcasting

In [38]:
# PyTorch will allow us to multiply things that are the same shape, as well as shapes where one operand is of size 1 in a given dimension.
# It also appends the leading dimensions of size 1 automatically.

In [39]:
torch.tensor([[1,2,3]]) + 10

tensor([[11, 12, 13]])

In [40]:
torch.tensor([[1, 2, 3]]) * torch.tensor([[10],[20],[30]]) # shape(1,3) * shape(3,1) = shape(3,3)

tensor([[10, 20, 30],
        [20, 40, 60],
        [30, 60, 90]])

In [41]:
torch.tensor([[1, 2, 3], [4, 5, 6]]) + torch.tensor([[[10, 20, 30]], [[40, 50, 60]]]) # shape(2,3) + shape(2, 1, 3) = shape(2,2,3)

tensor([[[11, 22, 33],
         [14, 25, 36]],

        [[41, 52, 63],
         [44, 55, 66]]])

## Named tensors

In [42]:
img_t = torch.randn(3, 5, 5) # shape(3,5,5) => shape [channels (RGB), rows, columns]
weights = torch.tensor([0.2126, 0.7152, 0.0722])
weights.shape

torch.Size([3])

In [43]:
batch_t = torch.randn(2, 3, 5, 5) # shape(2, 3, 5, 5) => shape [batch, channels (RGB), rows, columns]

In [44]:
img_gray_naive = img_t.mean(-3) # lazy, unweighted mean on dimension -3 (channel)
img_gray_naive

tensor([[ 1.2809,  1.3054, -0.6991, -0.6045,  0.6552],
        [-1.3861,  0.2665, -0.5745, -0.5562,  0.0225],
        [-0.1867, -0.2760, -1.1842, -0.0445, -0.2390],
        [-0.6503,  0.1319,  0.1842, -0.1270,  0.1079],
        [-0.0436, -0.3615,  0.5798,  0.4100, -0.4564]])

In [45]:
batch_gray_naive = batch_t.mean(-3) # again lazy, unweighted mean on dimension -3 (channel)
batch_gray_naive

tensor([[[ 0.8710, -0.9989,  0.3837,  0.5252,  0.2250],
         [-0.1418, -0.6348,  0.9891, -0.2628, -0.0894],
         [ 0.4954, -0.7363, -0.4325,  0.7441, -0.4196],
         [ 1.0778,  0.0652, -0.1964, -0.2270,  0.0534],
         [-0.0022,  0.2365, -0.8123, -0.8773, -0.4108]],

        [[ 0.0163, -0.0274, -0.7937, -0.9296, -0.9380],
         [-1.0693, -0.2237,  0.7874,  0.4136, -0.1685],
         [ 0.5220, -0.1247, -0.1570,  0.3906, -0.6009],
         [-0.8956,  0.4911, -0.1462,  0.1017, -0.0584],
         [-0.2687, -1.2854, -0.8739,  0.9642, -1.1154]]])

In [46]:
img_gray_naive.shape, batch_gray_naive.shape

(torch.Size([5, 5]), torch.Size([2, 5, 5]))

In [47]:
unsqueezed_weights = weights.unsqueeze(-1).unsqueeze(-1) # shape(3,1,1)
unsqueezed_weights

tensor([[[0.2126]],

        [[0.7152]],

        [[0.0722]]])

In [48]:
img_weights = img_t * unsqueezed_weights # shape(3,5,5)
img_weights

tensor([[[ 0.1979,  0.4797, -0.0684, -0.1088,  0.2133],
         [-0.2852,  0.1014,  0.0765, -0.1147,  0.1143],
         [ 0.0983, -0.3471, -0.0262, -0.0246, -0.1392],
         [ 0.1983,  0.2522, -0.2760,  0.0623,  0.1953],
         [-0.0130, -0.4275,  0.0733,  0.4939,  0.2017]],

        [[ 1.4473,  0.3834, -0.7820, -0.7606,  0.5969],
         [-1.3820, -0.0356, -1.4385, -0.4600,  0.0728],
         [-0.4327,  0.1260, -0.4961,  0.4205, -0.6009],
         [-0.7888, -0.0784,  0.6394,  0.1115,  0.4963],
         [-0.7609,  0.2247,  0.8433, -0.0573, -1.5444]],

        [[ 0.0641,  0.0811, -0.0493, -0.0172,  0.0092],
         [-0.0639,  0.0269, -0.0052, -0.0351, -0.0413],
         [-0.0301,  0.0454, -0.1975, -0.0437,  0.0562],
         [-0.1286, -0.0492,  0.0691, -0.0599, -0.0931],
         [ 0.0718,  0.0442,  0.0156, -0.0731, -0.0114]]])

In [49]:
batch_weights = batch_t * unsqueezed_weights # shape(2,3,5,5) remember that broadcasting appends the leading dimensions of size 1 automatically
batch_weights

tensor([[[[-8.1388e-02, -2.6555e-01,  1.8781e-01, -5.2415e-02,  1.7248e-01],
          [-7.2149e-02, -9.4470e-02, -7.9618e-04, -3.0439e-01,  1.9234e-01],
          [ 1.2502e-01, -6.4161e-02, -9.2501e-02,  3.1890e-01, -1.3403e-01],
          [ 1.3643e-01, -6.4564e-02,  1.4880e-01, -2.1727e-03, -1.9631e-02],
          [ 1.0245e-01,  2.8307e-03, -2.1613e-01, -1.3289e-01, -1.6035e-01]],

         [[ 1.6760e+00, -1.2792e+00,  3.1276e-01,  5.1214e-01,  1.4449e-01],
          [ 2.7790e-01, -3.4863e-01,  4.0546e-01, -4.2426e-01, -9.1585e-01],
          [ 4.9441e-01, -5.0538e-01,  5.7253e-01, -4.9227e-01, -1.4500e-01],
          [-4.1059e-01, -3.7619e-01, -5.6054e-01, -1.0936e+00,  9.5817e-02],
          [-2.0924e-01,  5.1178e-01, -8.8398e-01, -9.4805e-01,  2.0802e-01]],

         [[ 4.7105e-02,  2.9607e-03, -1.2245e-02,  7.9848e-02, -2.4419e-02],
          [-3.4262e-02, -7.0217e-02,  1.7358e-01,  8.9289e-02,  7.7717e-03],
          [ 1.4927e-02, -8.6682e-02, -1.2007e-01,  1.0257e-01, -3.0728e-

In [50]:
img_gray_weighted = img_weights.sum(-3) # sum on third dimension from the end (channel), shape(5,5)
img_gray_weighted

tensor([[ 1.7093,  0.9442, -0.8996, -0.8866,  0.8194],
        [-1.7311,  0.0927, -1.3672, -0.6098,  0.1458],
        [-0.3646, -0.1757, -0.7198,  0.3521, -0.6839],
        [-0.7191,  0.1247,  0.4325,  0.1139,  0.5986],
        [-0.7021, -0.1586,  0.9321,  0.3635, -1.3542]])

In [52]:
batch_gray_weighted = batch_weights.sum(-3) # sum on third dimension from the end (channel), shape(2,5,5)
batch_gray_weighted

tensor([[[ 1.6418, -1.5418,  0.4883,  0.5396,  0.2926],
         [ 0.1715, -0.5133,  0.5782, -0.6394, -0.7157],
         [ 0.6344, -0.6562,  0.3600, -0.0708, -0.3098],
         [-0.0456, -0.3667, -0.4482, -1.0338,  0.0848],
         [-0.1209,  0.5132, -1.1134, -1.1301, -0.0079]],

        [[ 0.7819, -0.3305,  0.1172, -1.2438, -1.5136],
         [-1.1252, -0.9475,  1.1835,  0.2032,  0.3088],
         [-0.1470,  0.3700, -0.1510,  0.7598, -0.8701],
         [-0.5141,  1.0813, -0.0278, -0.0407,  0.1664],
         [-0.0859, -1.1593, -1.3322,  0.7904, -1.3136]]])

In [53]:
batch_weights.shape, batch_t.shape, unsqueezed_weights.shape

(torch.Size([2, 3, 5, 5]), torch.Size([2, 3, 5, 5]), torch.Size([3, 1, 1]))

In [54]:
weights_named = torch.tensor([0.2126, 0.7152, 0.0722], names = ['channels'])
weights_named

/var/folders/bs/9j5t349d48g3lctd8l3l5l1r0000gn/T/ipykernel_48765/2163324119.py:1: UserWarning: Named tensors and all their associated APIs are an experimental feature and subject to change. Please do not use them for anything important until they are released as stable. (Triggered internally at /Users/runner/work/pytorch/pytorch/pytorch/c10/core/TensorImpl.h:1976.)
  weights_named = torch.tensor([0.2126, 0.7152, 0.0722], names = ['channels'])


tensor([0.2126, 0.7152, 0.0722], names=('channels',))

In [55]:
print(weights_named.shape, weights_named.names)

torch.Size([3]) ('channels',)


In [56]:
img_t_named = img_t.refine_names(..., 'channels', 'rows', 'columns')
batch_t_named = batch_t.refine_names(..., 'channels', 'rows', 'columns')
print("img named: ", img_t_named.shape, img_t_named.names)
print("batch named: ", batch_t_named.shape, batch_t_named.names)

img named:  torch.Size([3, 5, 5]) ('channels', 'rows', 'columns')
batch named:  torch.Size([2, 3, 5, 5]) (None, 'channels', 'rows', 'columns')


In [ ]:
# For operations with two inputs, in addition to the usual dimension checks—whether sizes are the same, 
# or if one is 1 and can be broadcast to the other—PyTorch will now check the names for us. 
# So far, it does not automatically align dimensions, so we need to do this explicitly.
# The method align_as returns a tensor with missing dimensions added and existing ones permuted to the right order

In [58]:
weights_named_aligned = weights_named.align_as(img_t_named)
weights_named_aligned.shape, weights_named_aligned.names

(torch.Size([3, 1, 1]), ('channels', 'rows', 'columns'))

In [59]:
# Functions accepting dimension arguments, like sum, also take named dimensions
gray_named = (img_t_named * weights_named_aligned).sum('channels')
gray_named

tensor([[ 1.7093,  0.9442, -0.8996, -0.8866,  0.8194],
        [-1.7311,  0.0927, -1.3672, -0.6098,  0.1458],
        [-0.3646, -0.1757, -0.7198,  0.3521, -0.6839],
        [-0.7191,  0.1247,  0.4325,  0.1139,  0.5986],
        [-0.7021, -0.1586,  0.9321,  0.3635, -1.3542]],
       names=('rows', 'columns'))

In [61]:
img_t_named[...,:3]

tensor([[[ 0.9309,  2.2562, -0.3216],
         [-1.3414,  0.4770,  0.3597],
         [ 0.4624, -1.6325, -0.1233],
         [ 0.9329,  1.1865, -1.2982],
         [-0.0610, -2.0109,  0.3446]],

        [[ 2.0236,  0.5361, -1.0934],
         [-1.9323, -0.0498, -2.0113],
         [-0.6050,  0.1762, -0.6936],
         [-1.1030, -0.1096,  0.8941],
         [-1.0640,  0.3141,  1.1791]],

        [[ 0.8881,  1.1238, -0.6823],
         [-0.8846,  0.3724, -0.0720],
         [-0.4175,  0.6283, -2.7356],
         [-1.7809, -0.6811,  0.9566],
         [ 0.9942,  0.6123,  0.2156]]], names=('channels', 'rows', 'columns'))

In [63]:
# gray_named = (img_t_named[...,:3] * weights_named).sum('channels') # doesn't work

RuntimeError: Error when attempting to broadcast dims ['channels', 'rows', 'columns'] and dims ['channels']: dim 'columns' and dim 'channels' are at the same position from the right but do not match.

In [64]:
# If we want to use tensors outside functions that operate on named tensors, we need to drop the names by renaming them to None.
# The following gets us back into the world of unnamed dimensions
gray_plain = gray_named.rename(None)
gray_plain.shape, gray_plain.names

(torch.Size([5, 5]), (None, None))