In [1]:
import torchvision
from torchvision import models

In [2]:
# models.list_models()

## AlexNet

In [3]:
# alexnet = models.AlexNet()

## Visual Transformer

In [4]:
vit = models.vit_b_16(weights=models.ViT_B_16_Weights.IMAGENET1K_V1)

In [5]:
# vit

In [6]:
from torchvision import transforms

In [7]:
preprocess = transforms.Compose([
    transforms.Resize(256),
    transforms.CenterCrop(224),
    transforms.ToTensor(),
    transforms.Normalize(mean=[0.485, 0.456, 0.406],std=[0.229, 0.224, 0.225])
])

In [8]:
from PIL import Image

In [9]:
img = Image.open("../data/p1ch02/airplane.jpeg")

In [10]:
# img

In [11]:
img_t = preprocess(img)
img_t

tensor([[[1.1187, 1.1187, 1.1015,  ..., 1.1015, 1.1358, 1.1358],
         [1.1187, 1.1187, 1.1015,  ..., 1.0673, 1.0844, 1.1015],
         [1.1015, 1.1015, 1.1015,  ..., 1.0159, 1.0502, 1.0502],
         ...,
         [0.7933, 0.8104, 0.8276,  ..., 0.5536, 0.4508, 0.2282],
         [0.2796, 0.2624, 0.2796,  ..., 0.5193, 0.3994, 0.1426],
         [0.1597, 0.2453, 0.3138,  ..., 0.4851, 0.3138, 0.0398]],

        [[1.3431, 1.3431, 1.3256,  ..., 1.4132, 1.4307, 1.4482],
         [1.3431, 1.3431, 1.3256,  ..., 1.3782, 1.3957, 1.3957],
         [1.3256, 1.3256, 1.3256,  ..., 1.3782, 1.3606, 1.3606],
         ...,
         [1.0630, 1.0805, 1.0980,  ..., 0.8004, 0.6604, 0.4328],
         [0.5028, 0.4678, 0.4853,  ..., 0.7479, 0.5903, 0.3452],
         [0.3627, 0.4503, 0.5028,  ..., 0.6779, 0.5028, 0.2402]],

        [[1.7685, 1.7685, 1.7511,  ..., 1.9428, 1.9428, 1.9428],
         [1.7685, 1.7685, 1.7511,  ..., 1.9080, 1.9080, 1.9254],
         [1.7511, 1.7511, 1.7511,  ..., 1.8731, 1.8905, 1.

In [12]:
print(img_t.shape)

torch.Size([3, 224, 224])


In [13]:
import torch
batch_t = torch.unsqueeze(img_t, 0)
batch_t

tensor([[[[1.1187, 1.1187, 1.1015,  ..., 1.1015, 1.1358, 1.1358],
          [1.1187, 1.1187, 1.1015,  ..., 1.0673, 1.0844, 1.1015],
          [1.1015, 1.1015, 1.1015,  ..., 1.0159, 1.0502, 1.0502],
          ...,
          [0.7933, 0.8104, 0.8276,  ..., 0.5536, 0.4508, 0.2282],
          [0.2796, 0.2624, 0.2796,  ..., 0.5193, 0.3994, 0.1426],
          [0.1597, 0.2453, 0.3138,  ..., 0.4851, 0.3138, 0.0398]],

         [[1.3431, 1.3431, 1.3256,  ..., 1.4132, 1.4307, 1.4482],
          [1.3431, 1.3431, 1.3256,  ..., 1.3782, 1.3957, 1.3957],
          [1.3256, 1.3256, 1.3256,  ..., 1.3782, 1.3606, 1.3606],
          ...,
          [1.0630, 1.0805, 1.0980,  ..., 0.8004, 0.6604, 0.4328],
          [0.5028, 0.4678, 0.4853,  ..., 0.7479, 0.5903, 0.3452],
          [0.3627, 0.4503, 0.5028,  ..., 0.6779, 0.5028, 0.2402]],

         [[1.7685, 1.7685, 1.7511,  ..., 1.9428, 1.9428, 1.9428],
          [1.7685, 1.7685, 1.7511,  ..., 1.9080, 1.9080, 1.9254],
          [1.7511, 1.7511, 1.7511,  ..., 1

In [14]:
print(batch_t.shape)

torch.Size([1, 3, 224, 224])


### inference

In [15]:
vit.eval();

In [16]:
out = vit(batch_t)
print(out)
print(out.shape)

tensor([[ 1.2497e-01, -5.2205e-01, -2.7098e-01, -2.1889e-02, -4.2231e-01,
         -9.5991e-02, -4.5199e-01, -2.4197e-01, -1.5946e-01, -2.5865e-01,
          1.9858e-01,  3.4599e-01,  2.7319e-01, -2.5678e-01,  8.7169e-01,
          4.7721e-02,  1.6816e-01, -4.5781e-01,  4.1136e-02, -2.2560e-01,
         -2.7201e-01,  8.8759e-03,  1.9083e-01,  1.5794e-01,  4.4115e-01,
          4.6094e-01,  3.1512e-01, -4.6773e-01,  6.2235e-01,  4.5548e-02,
         -3.4802e-02,  1.5016e-01, -3.5875e-01,  1.8602e-02,  3.2230e-01,
          2.1631e-01,  2.6151e-01, -4.8953e-01,  3.6902e-01, -2.9640e-02,
         -2.5835e-01, -3.6717e-02,  2.8049e-01, -2.1223e-01, -3.4376e-01,
         -1.3767e-02, -1.5674e-01, -1.1880e-01, -6.7535e-01, -9.8600e-02,
          8.9735e-02, -5.1663e-01,  2.3898e-02, -5.6895e-01, -1.0279e-01,
         -9.1980e-02,  3.0081e-01, -6.3588e-01, -6.7085e-02, -1.7590e-02,
         -4.5600e-01, -2.3424e-01,  2.3983e-01, -1.3373e-01,  3.7131e-01,
          1.7741e-02, -6.4541e-02, -5.

In [17]:
with open('../data/p1ch02/imagenet_classes.txt') as f:
    labels = [line.strip() for line in f.readlines()]

In [18]:
_, index = torch.max(out, 1)
#print(index)
#percentage = torch.nn.functional.softmax(out, dim=1)
#print(percentage)
percentage = torch.nn.functional.softmax(out, dim=1)[0] * 100
labels[index.item()], percentage[index.item()].item()

('airliner', 44.088993072509766)

In [19]:
_, indices = torch.sort(out, descending=True)
[(labels[idx], percentage[idx].item()) for idx in indices[0][:5]]

[('airliner', 44.088993072509766),
 ('wing', 39.73176193237305),
 ('bullet train, bullet', 0.09713304787874222),
 ('warplane, military plane', 0.06916385143995285),
 ('medicine chest, medicine cabinet', 0.051803380250930786)]