In [1]:
import torchvision
from torchvision import models

In [2]:
# models.list_models()

## AlexNet

In [3]:
# alexnet = models.AlexNet()

## Visual Transformer

In [4]:
vit = models.vit_b_16(weights=models.ViT_B_16_Weights.IMAGENET1K_V1)

In [5]:
# vit

In [6]:
from torchvision import transforms

In [7]:
preprocess = transforms.Compose([
    transforms.Resize(256),
    transforms.CenterCrop(224),
    transforms.ToTensor(),
    transforms.Normalize(mean=[0.485, 0.456, 0.406],std=[0.229, 0.224, 0.225])
])

In [8]:
from PIL import Image

In [9]:
img = Image.open("../data/p1ch02/airplane.jpeg")

In [10]:
# img

In [11]:
img_t = preprocess(img)
img_t

tensor([[[1.1187, 1.1187, 1.1015,  ..., 1.1015, 1.1358, 1.1358],
         [1.1187, 1.1187, 1.1015,  ..., 1.0673, 1.0844, 1.1015],
         [1.1015, 1.1015, 1.1015,  ..., 1.0159, 1.0502, 1.0502],
         ...,
         [0.7933, 0.8104, 0.8276,  ..., 0.5536, 0.4508, 0.2282],
         [0.2796, 0.2624, 0.2796,  ..., 0.5193, 0.3994, 0.1426],
         [0.1597, 0.2453, 0.2967,  ..., 0.4851, 0.3138, 0.0398]],

        [[1.3431, 1.3431, 1.3256,  ..., 1.4132, 1.4307, 1.4482],
         [1.3431, 1.3431, 1.3256,  ..., 1.3782, 1.3957, 1.3957],
         [1.3256, 1.3256, 1.3256,  ..., 1.3782, 1.3606, 1.3606],
         ...,
         [1.0630, 1.0805, 1.0980,  ..., 0.8004, 0.6604, 0.4328],
         [0.5028, 0.4678, 0.4853,  ..., 0.7479, 0.5903, 0.3452],
         [0.3627, 0.4503, 0.5028,  ..., 0.6779, 0.5028, 0.2402]],

        [[1.7685, 1.7685, 1.7511,  ..., 1.9428, 1.9428, 1.9428],
         [1.7685, 1.7685, 1.7511,  ..., 1.9080, 1.9080, 1.9254],
         [1.7511, 1.7511, 1.7511,  ..., 1.8731, 1.8905, 1.

In [12]:
print(img_t.shape)

torch.Size([3, 224, 224])


In [13]:
import torch
batch_t = torch.unsqueeze(img_t, 0)
batch_t

tensor([[[[1.1187, 1.1187, 1.1015,  ..., 1.1015, 1.1358, 1.1358],
          [1.1187, 1.1187, 1.1015,  ..., 1.0673, 1.0844, 1.1015],
          [1.1015, 1.1015, 1.1015,  ..., 1.0159, 1.0502, 1.0502],
          ...,
          [0.7933, 0.8104, 0.8276,  ..., 0.5536, 0.4508, 0.2282],
          [0.2796, 0.2624, 0.2796,  ..., 0.5193, 0.3994, 0.1426],
          [0.1597, 0.2453, 0.2967,  ..., 0.4851, 0.3138, 0.0398]],

         [[1.3431, 1.3431, 1.3256,  ..., 1.4132, 1.4307, 1.4482],
          [1.3431, 1.3431, 1.3256,  ..., 1.3782, 1.3957, 1.3957],
          [1.3256, 1.3256, 1.3256,  ..., 1.3782, 1.3606, 1.3606],
          ...,
          [1.0630, 1.0805, 1.0980,  ..., 0.8004, 0.6604, 0.4328],
          [0.5028, 0.4678, 0.4853,  ..., 0.7479, 0.5903, 0.3452],
          [0.3627, 0.4503, 0.5028,  ..., 0.6779, 0.5028, 0.2402]],

         [[1.7685, 1.7685, 1.7511,  ..., 1.9428, 1.9428, 1.9428],
          [1.7685, 1.7685, 1.7511,  ..., 1.9080, 1.9080, 1.9254],
          [1.7511, 1.7511, 1.7511,  ..., 1

In [14]:
print(batch_t.shape)

torch.Size([1, 3, 224, 224])


### inference

In [15]:
vit.eval();

In [16]:
out = vit(batch_t)
print(out)
print(out.shape)

tensor([[ 1.2572e-01, -5.1803e-01, -2.6723e-01, -2.0149e-02, -4.1932e-01,
         -9.4836e-02, -4.5151e-01, -2.4269e-01, -1.5969e-01, -2.5963e-01,
          2.0065e-01,  3.4544e-01,  2.7309e-01, -2.5495e-01,  8.7026e-01,
          4.6251e-02,  1.6753e-01, -4.5829e-01,  3.9214e-02, -2.2399e-01,
         -2.7389e-01,  1.1353e-02,  1.9159e-01,  1.5721e-01,  4.3900e-01,
          4.5816e-01,  3.1254e-01, -4.6833e-01,  6.2086e-01,  4.8353e-02,
         -3.6176e-02,  1.4843e-01, -3.6083e-01,  1.8690e-02,  3.2159e-01,
          2.1284e-01,  2.6089e-01, -4.8979e-01,  3.6625e-01, -3.3820e-02,
         -2.6028e-01, -4.0027e-02,  2.7834e-01, -2.1312e-01, -3.4456e-01,
         -1.6785e-02, -1.5903e-01, -1.2132e-01, -6.7643e-01, -1.0035e-01,
          8.8782e-02, -5.1517e-01,  2.2545e-02, -5.7130e-01, -1.0553e-01,
         -9.3731e-02,  2.9857e-01, -6.3681e-01, -6.8721e-02, -1.8747e-02,
         -4.5798e-01, -2.3703e-01,  2.4060e-01, -1.3468e-01,  3.6936e-01,
          1.7703e-02, -6.6265e-02, -5.

In [17]:
with open('../data/p1ch02/imagenet_classes.txt') as f:
    labels = [line.strip() for line in f.readlines()]

In [18]:
_, index = torch.max(out, 1)
#print(index)
#percentage = torch.nn.functional.softmax(out, dim=1)
#print(percentage)
percentage = torch.nn.functional.softmax(out, dim=1)[0] * 100
labels[index.item()], percentage[index.item()].item()

('airliner', 44.15442657470703)

In [19]:
_, indices = torch.sort(out, descending=True)
[(labels[idx], percentage[idx].item()) for idx in indices[0][:5]]

[('airliner', 44.15442657470703),
 ('wing', 39.67776870727539),
 ('bullet train, bullet', 0.09658630937337875),
 ('warplane, military plane', 0.06937438994646072),
 ('medicine chest, medicine cabinet', 0.05175714194774628)]